# Generated by Django 5.1.4 on 2025-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topText', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('orderNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'experience_map',
                'managed': False,
            },
        ),
    ]
